### ISSUE TITLE
Got error while running first apply

### ISSUE THREAD

**Issue by boris-smph** [idealo/terraform-aws-mwaa#156]
Hello,

I am trying the module without any modificaiton. Using version 3.0.1

> Error: creating MWAA Environment (prod): ValidationException: Failed to assume role arn:aws:iam::REDACTED:role/mwaa-prod-execution-role. This could be due to the role's trust policy. Please ensure your role is assumable by 'airflow-env.amazonaws.com' Service Principal and try again.

```
│   with module.experimental.module.mwaa.aws_mwaa_environment.this,
│   on modules/mwaa/main.tf line 1, in resource "aws_mwaa_environment" "this":
│    1: resource "aws_mwaa_environment" "this" {
```

My AWS Provider is 5.24.0 and terraform is version 1.6.3.

**Comment by mgerlach** [comment]
Hi @boris-smph , thanks for submitting this issue.

We do define that trust policy for airflow-env.amazonaws.com here: https://github.com/idealo/terraform-aws-mwaa/blob/main/iam.tf#L19 

Could you post the full code that calls this module?

**Comment by boris-smph** [comment]
Here is how I call the module.

```
module "mwaa" {
  source       = "../modules/mwaa"
  account_id = "REDACTED"
  region = "us-east-2"
  environment_name = "prod"
  internet_gateway_id = "igw-REDACTED"
  vpc_id = "vpc-REDACTED"

  public_subnet_cidrs  = ["172.31.1.0/24","172.31.2.0/24"]
  private_subnet_cidrs = ["172.31.3.0/24","172.31.4.0/24"]
  source_bucket_arn = "arn:aws:s3:::mwaa.REDACTED.com"
}
```

I have in iam.tf:

```

 13 data "aws_iam_policy_document" "assume" {
 14   version = "2012-10-17"
 15   statement {
 16     effect  = "Allow"
 17     principals {
 18       identifiers = [
 19         "airflow-env.amazonaws.com",
 20         "airflow.amazonaws.com"
 21       ]
 22       type        = "Service"
 23     }
 24     actions = [
 25       "sts:AssumeRole"
 26     ]
 27   }
 28 }
```

**Comment by boris-smph** [comment]
I switched to another zone (the main one I use) and it worked.

**Comment by mgerlach** [comment]
Sorry for the delay, glad it works now! Still, I find this a bit confusing. By "zone", do you mean AWS region?
