### ISSUE TITLE
Missing DAGs when setting logs level to `DEBUG`

### ISSUE THREAD

**Issue by git-taufiq** [idealo/terraform-aws-mwaa#157]
Below snippet of the module:
```
module "mwaa" {
  source = "idealo/mwaa/aws"
  version = 3.0.0
  airflow_version = "2.5.1"
  ...
  webserver_logs_level = "INFO"
  worker_logs_level = "DEBUG"
  task_logs_level = "INFO"
  scheduler_logs_level = "DEBUG"
  dag_processing_logs_level =  "DEBUG"
}
```
Somehow all DAGs are missing/not showing when setting log levels to "DEBUG" for apply a new Airflow environment. I do not have any issue when setting those `DEBUG` log levels to `WARNING`.

**Comment by mgerlach** [comment]
Hi @git-taufiq maybe Airflow is just logging too much at debug so DAG creation takes a long time?

**Comment by mgerlach** [comment]
Hi @git-taufiq is this still an issue, or can we close?

**Comment by mgerlach** [comment]
Closed due to no response from author. Pls reopen if still an issue
