### ISSUE TITLE
Unable to check PublicAccessBlock configuration for the account

### ISSUE THREAD

**Issue by bryzgaloff** [idealo/terraform-aws-mwaa#37]
Here is my configuration:

```terraform
module "airflow" {
  source = "idealo/mwaa/aws"
  version = "0.2.1"

  account_id = data.aws_caller_identity.current.account_id
  environment_name = "airflow"
  region = data.aws_region.current.name

  create_networking_config = true
  private_subnet_cidrs = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnet_cidrs = ["10.0.3.0/24", "10.0.4.0/24"]
  vpc_id = aws_vpc.mwaa.id
  internet_gateway_id = aws_internet_gateway.mwaa.id

  airflow_version = "2.0.2"
  dag_s3_path = "/dags-src"
  environment_class = "mw1.small"

  max_workers = 10
  min_workers = 1

  source_bucket_arn = aws_s3_bucket.mwaa.arn

  webserver_access_mode = "PRIVATE_ONLY"
}

data "aws_caller_identity" "current" {}

data "aws_region" "current" {}

resource "aws_s3_bucket" "mwaa" {  # dags, requirements, plugins
  bucket = "…"  # some valid bucket name
}
output "mwaa-dags-bucket-name" {
  value = aws_s3_bucket.mwaa.id
}

resource "aws_vpc" "mwaa" {
  cidr_block = "10.0.0.0/16"  # arbitrary chosen from documentation
}

resource "aws_internet_gateway" "mwaa" {
  vpc_id = aws_vpc.mwaa.id
}
```

I have encountered the following error:
```
Error: error creating MWAA Environment: ValidationException: Unable to check PublicAccessBlock configuration for the account …: Access Denied (Service: S3Control, Status Code: 403, Request ID: …, Extended Request ID: …)
```

The bucket mentioned on the configuration did not exist by the time I have applied it. Meaning the bucket has been created by this configuration. Also Terraform AWS provider documentation [states](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#acl) that `acl = "private"` by default. However, once I have opened permissions of the newly created bucket, its «Block all public access» was **disabled**:

<img width="446" alt="Снимок экрана 2021-12-08 в 23 03 21" src="https://user-images.githubusercontent.com/15062597/145276342-6bcfd214-4ea0-4c22-b693-fac0ba53e956.png">

Meaning public access was allowed. The issue was resolved once I have disabled this permission. Do I get something wrong about S3 buckets creation? E.g. explicitly set `acl = "private"`?

**Comment by mgerlach** [comment]
Hi @bryzgaloff , just to clarify, are you saying that your configuration above did not work and that you had to enable public access to the new bucket for it to work? Or did the configuration work (MWAA and all resources created) and you are just wondering how to correctly configure the bucket?

FYI we are using a module to create the bucket with maximum security as follows:
```hcl
module "s3_bucket_mwaa" {
  source = "terraform-aws-modules/s3-bucket/aws"
  version = "2.11.1"
  bucket = "..."  # name
  block_public_acls = true
  restrict_public_buckets = true
  block_public_policy = true
  ignore_public_acls = true
  attach_deny_insecure_transport_policy = true
  acl = "private"
  ... # not relevant for this
  server_side_encryption_configuration = {
    rule = {
      apply_server_side_encryption_by_default = {
        sse_algorithm = "AES256"
      }
    }
  }
}
```

**Comment by bryzgaloff** [comment]
> are you saying that your configuration above did not work and that you had to enable public access to the new bucket for it to work? Or did the configuration work (MWAA and all resources created) and you are just wondering how to correctly configure the bucket?

The resources failed to create initially. MWAA env itself in particular. I did it the following way:
1. `terraform apply` for the config mentioned above.
2. Some resources have been created, including the bucket. But `ValidationException: Unable to check PublicAccessBlock` has appeared. So I have opened the S3 console and disabled public access for this bucket manually.
3. Run `terraform apply` once again and MWAA env creation has also completed successfully.

Could you please provide a complete configuration you use to deploy MWAA env? Have you configured `aws_vpc` and `aws_internet_gateway` somehow in a special way either?

I like you S3 bucket configuration using module. Don't you know, is it possible for me to rewrite the configuration and replace my "native" S3 bucket creation with your module?

**Comment by mgerlach** [comment]
Hi @bryzgaloff ,

To be honest, when we set up MWAA first, we also started without the s3-bucket module. Also it's possible that we had to initially open the bucket, then secure it again. Maybe @jdiebold remembers the details? We would have to test and either fix or update the README. 

As for VPC and internet gateway, there is no need for special configuration, only the public and private CIDR blocks have to match. You can also have the module create the networking resources for you. 

To answer your thirs question, yes you can switch to using the s3-bucket module:
1. Change your code to use the s3-bucket module (for the following I assume you name it "s3_bucket_mwaa" as in my example), but use the same settings (name, acl, security, ...) as with the "native" resource (matching the actual bucket in AWS)
2. Run terraform plan to see the new Terraform resource id for the bucket: It should look like `module.s3_bucket_mwaa.aws_s3_bucket.<generated_id> 
3. Run `terraform state mv aws_s3_bucket.mwaa module.s3_bucket_mwaa.aws_s3_bucket.<generated_id from plan>` (see also https://www.terraform.io/docs/cli/commands/state/mv.html)
4. Now you can make changes to the bucket configuration

**Comment by bryzgaloff** [comment]
In fact `acl = "private"` is not enough to block all public access. This is doable using a separate resource (weird, I know): https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block

Also `acl = "private"` is default. And yes, bucket can be with access granted to owner only (private ACL) and with block-public-access=false.

I suggest you adding this moment to your repo readme so that newcomers will create a bucket in a right way.

**Comment by bryzgaloff** [comment]
Here is a minimal bucket configuration:

```terraform
resource "aws_s3_bucket" "mwaa" {
  bucket = "…"
  versioning {
    # required: https://docs.aws.amazon.com/mwaa/latest/userguide/mwaa-s3-bucket.html
    enabled = true
  }
}
resource "aws_s3_bucket_public_access_block" "mwaa" {
  # required: https://docs.aws.amazon.com/mwaa/latest/userguide/mwaa-s3-bucket.html
  bucket                  = aws_s3_bucket.mwaa.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
```

**Comment by mgerlach** [comment]
Thanks for the suggestions @bryzgaloff . Good idea to mention this in the docs. Will work on this in January.

We are aware of the public access block resource. The s3-bucket module is taking care of that. Btw I think versioning is not a requirement for the bucket, but probably a good practice.

**Comment by bryzgaloff** [comment]
> Btw I think versioning is not a requirement for the bucket

From [docs](https://docs.aws.amazon.com/mwaa/latest/userguide/mwaa-s3-bucket.html):

> An Amazon S3 bucket used for an Amazon MWAA environment must be configured to Block all public access, with **Bucket Versioning enabled**.

**Comment by mgerlach** [comment]
> > Btw I think versioning is not a requirement for the bucket
> 
> From [docs](https://docs.aws.amazon.com/mwaa/latest/userguide/mwaa-s3-bucket.html):
> 
> > An Amazon S3 bucket used for an Amazon MWAA environment must be configured to Block all public access, with **Bucket Versioning enabled**.
> 
> However, in fact this is not checked by MWAA readiness polling script.

Exactly. We had it enabled initially and then suspended versioning as we have the DAG history also in GitHub for recovery or reverting purposes. Not sure if MWAA really uses the object versions or whether it's just a general best practice recommendation. I think we'll just mention the minimal bucket config as you suggested above (with versioning enabled).
