### ISSUE TITLE
aws_route_table.public[0]

### ISSUE THREAD

**Issue by bryzgaloff** [idealo/terraform-aws-mwaa#41]
Public and private table route associations configuration differ (permalinks to current `main` state):
https://github.com/idealo/terraform-aws-mwaa/blob/392421ea7458a9d8d21bdb7b1c4fddcd3b482396/vpc.tf#L61
https://github.com/idealo/terraform-aws-mwaa/blob/392421ea7458a9d8d21bdb7b1c4fddcd3b482396/vpc.tf#L79

Is it intended that public association is mapped to `aws_route_table.public[0]` only? Meaning nothing is associated with `aws_route_table.public[1]`.

Should not it be `route_table_id = aws_route_table.public[count.index].id` either?

**Comment by mgerlach** [comment]
@jdiebold ?

**Comment by mgerlach** [comment]
Will work on this in January.

**Comment by jdiebold** [comment]
@bryzgaloff you need only one public route table, so it worked but created one public route table that wasn't used. we removed it now with 0.2.3.
Thanks for discovering!
