### ISSUE TITLE
BUG! Hardcoded region in KMS policy

### ISSUE THREAD

**Issue by anton-cloudthread** [idealo/terraform-aws-mwaa#42]
Guys, you f**king owe my company 5 hours of my work now! 😆 

Why is `eu-central-1` hard-coded here??

https://github.com/idealo/terraform-aws-mwaa/blob/1290886217df7fca54b22e1dd2587f44b2c2cf2f/iam.tf#L115

It has to be `"sqs.${var.region}.amazonaws.com"`. Funny thing it worked in my dev environment cuz it is located in eu-central-1 while failed in production because it is another region! 😅 

I will describe unexpected behaviour here for others to google just in case. Airflow cannot start any task writing down the following to the task log:
```
*** Reading remote log from Cloudwatch log_group: airflow-airflow-Task log_stream: sample/sample/2021-12-23T20_35_46.162793+00_00/1.log.
Could not read remote logs from log_group: airflow-airflow-Task log_stream: sample/sample/2021-12-23T20_35_46.162793+00_00/1.log.
```

No tasks could not start and also no log streams have been created on the log group. Please fix and release a new version ASAP! CC @mgerlach

**Comment by mgerlach** [comment]
@anton-cloudthread Sorry about that. We are only in eu-central-1, which is probably the reason for this having slipped through unnoticed.

@jdiebold looks like we need better quality control for our open source modules... Can you release during your on-call time?
