### ISSUE TITLE
Support Airflow 2.2.2

### ISSUE THREAD

**Issue by mgerlach** [idealo/terraform-aws-mwaa#65]
Airflow 2.2.2 is now supported by MWAA.

We should ensure this module properly supports MWAA with Airflow 2.2.2. Once ensured, the default version should be set to 2.2.2 (currently it's 2.0.2) and a major release should be published.

Upgrade instructions from AWS are not very complicated: https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-versions.html#airflow-versions-upgrading

We should also monitor https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mwaa_environment for 2.2.2-related changes/additions of the base terraform resource

**Comment by jdiebold** [comment]
We have deployed the current version of the module with airflow_version set to 2.2.2, works perfectly find.
Be aware, that a simple update of an existing environment is not possible (also not via terraform). You have to tear down the old environment and create a new one. Unforturnately you'll lose your history. [see MWAA docs](https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-versions.html#airflow-versions-upgrading)
